services:
  db:
    image: postgres:17.0
    command: -p $DB_PORT
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      TZ: $TIMEZONE
      PGTZ: $TIMEZONE
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
  backend:
    restart: on-failure
    build: ./backend
    command: fastapi dev main.py --host 0.0.0.0 --port $BE_PORT
    ports:
      - "$BE_PORT:$BE_PORT"
    volumes:
      - ./backend:/app
    environment:
      - TZ=$TIMEZONE
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/home/app:cached
      - /home/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_APP_API_URL=$PROTOCOL://$DOMAIN:$BE_PORT/
    ports:
      - $FE_PORT:$FE_PORT
    command: npm run dev

volumes:
  db-data:
  backend:
  frontend:
